# Welcome to Jekyll!
#

# Site settings
title: Shema Amp Co
description: |
  Hand-built guitar amplifiers<br />
  made in Nashville, Tennessee.

owner: Shema Amp Co # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: shemaamp@gmail.com.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shemaamp.com" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  facebook-official:
    url: https://facebook.com/shemaampco
    icon: fa fa-2x fa-facebook-square
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email:
    url: shemaampco@gmail.com
    icon: fa fa-2x fa-facebook-square
  #flickr:
  instagram:
    url: http://instagram.com/shemaampco
    icon: fa fa-2x fa-facebook-square

  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
